#!/usr/bin/env bash

# Steps:
#  1. copy the output from buildroot to the bin directory
#  2. run qemu with the right parameters

mkdir -p bin/
# TODO: Need to add a check here to make sure we don't overwrite progress if
# the player has already started playing.
cp buildroot/output/images/* bin/
qemu-system-arm -M virt -cpu cortex-a15 -m 256 \
    -kernel bin/zImage -append "root=/dev/vda console=ttyS0" \
    -drive file=bin/rootfs.ext2,format=raw,index=0,media=disk \
    -chardev file,id=log,path=./log.txt \
    -chardev pty,id=gdb \
    -device pci-serial,chardev=log \
    -device pci-serial,chardev=gdb \
    -serial stdio \
    -serial chardev:log \
    -serial chardev:gdb \
    -nographic -monitor none
